# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RXSwift_App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RXSwift_App
    pod 'RxSwift'
    pod 'RxCocoa'

  target 'RXSwift_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RXSwift_AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
